
CREATE TABLE ACCOUNT (
    ACC_ID       BIGINT NOT NULL,
    ACC_NAME     VARCHAR(64) NOT NULL,
    ACC_BAL    	 INT NOT NULL,
    PRIMARY KEY (ACC_ID)
);




CREATE TABLE KIR (
    KIR_ID       BIGINT NOT NULL,
    KIR_NAME     VARCHAR(64) NOT NULL,
    KIR_BAL    	 INT NOT NULL,
    PRIMARY KEY (KIR_ID)
);
