
CREATE TABLE ACCOUNT (
    ACC_ID       BIGINT NOT NULL,
    ACC_HOLDER   BIGINT NOT NULL, 
    ACC_BAL    	 INT NOT NULL,
    PRIMARY KEY (ACC_ID,ACC_BAL)
);




CREATE TABLE PERSON (
    P_ID       BIGINT NOT NULL,
    P_NAME     VARCHAR(64) NOT NULL,
    P_ADDRESS   VARCHAR(64),
    PRIMARY KEY (P_ID)
);
